// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.IntegrationRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.IntegrationFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Integration}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.IntegrationRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.IntegrationFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Integration}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.IntegrationRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.IntegrationFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Integration}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ManagerRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ManagerFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Manager}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ManagerRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ManagerFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Manager}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ManagerRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ManagerFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Manager}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ServiceDataRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ServiceDataFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.ServiceData}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ServiceDataRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ServiceDataFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.ServiceData}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ServiceDataRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ServiceDataFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.ServiceData}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ApplicationDataRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ApplicationFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.ApplicationData}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ApplicationDataRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ApplicationFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.ApplicationData}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ApplicationDataRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ApplicationFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.ApplicationData}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.FeedbackRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.FeedbackFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Feedback}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.FeedbackRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.FeedbackFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Feedback}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.FeedbackRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.FeedbackFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Feedback}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.IncidentRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.IncidentFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Incident}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.IncidentRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.IncidentFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Incident}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.IncidentRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.IncidentFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Incident}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.MemberRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.MemberFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Member}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.MemberRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.MemberFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Member}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.MemberRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.MemberFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Member}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.RepoRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.RepoFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Repo}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.RepoRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.RepoFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Repo}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.RepoRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.RepoFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Repo}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ResponsibleRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ResponsibleFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Responsible}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ResponsibleRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ResponsibleFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Responsible}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.ResponsibleRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.ResponsibleFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Responsible}}")]
[assembly: SuppressMessage("Globalization", "CA1304:Especificar CultureInfo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.SquadRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.SquadFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Squad}}")]
[assembly: SuppressMessage("Performance", "CA1862:Use as sobrecargas do método 'StringComparison' para realizar comparações de strings que não diferenciam maiúsculas de minúsculas", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.SquadRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.SquadFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Squad}}")]
[assembly: SuppressMessage("Globalization", "CA1311:Especifique uma cultura ou use uma versão invariável", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Infrastructure.Data.Repositories.SquadRepository.GetListAsync(Stellantis.ProjectName.Application.Models.Filters.SquadFilter)~System.Threading.Tasks.Task{Stellantis.ProjectName.Application.Models.Filters.PagedResult{Stellantis.ProjectName.Domain.Entities.Squad}}")]
