image: 253882794486.dkr.ecr.us-east-1.amazonaws.com/build-tools:master-net8

include:
  - project: "fca/architecture/IaC/cloud-digital/common-ci"
    file: "/job-commons.yml"
  - project: 'fca/architecture/IaC/cloud-digital/common-ci'  
    file: 'job-commons-sqube.yml'

variables:
  REPOSITORY_URL: 924431524709.dkr.ecr.us-east-1.amazonaws.com/digital-esb-app-esb-baseproject-esb

stages:
  - test
  - quality
  - build

before_script:
  - IMAGE_TAG="$(echo $CI_COMMIT_SHA | head -c 8)"
  - VERSION=$(date +"%Y%m%d%H%M")
  - echo $IMAGE_TAG $CI_COMMIT_REF_NAME $VERSION
  - echo $REPOSITORY_URL

test:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
    - mkdir -p ./src/artifacts
    - dotnet test ./src/Application.Tests/Application.Tests.csproj --verbosity normal --logger:"junit;LogFilePath=../artifacts/{assembly}-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    - dotnet test ./src/Domain.Tests/Domain.Tests.csproj --verbosity normal --logger:"junit;LogFilePath=../artifacts/{assembly}-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    - dotnet test ./src/Infrastructure.Tests/Infrastructure.Tests.csproj --verbosity normal --logger:"junit;LogFilePath=../artifacts/{assembly}-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
    - dotnet test ./src/WebApi.Tests/WebApi.Tests.csproj --verbosity normal --logger:"junit;LogFilePath=../artifacts/{assembly}-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./src/artifacts/*-result.xml
    reports:
      junit:
        - ./src/artifacts/*-result.xml

sonarqube:
  image: 253882794486.dkr.ecr.us-east-1.amazonaws.com/build-tools:latest-devops-master
  stage: quality
  script:
    - apt-get update && apt-get install -y dotnet-sdk-8.0
    - dotnet tool install --global dotnet-coverage
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet restore ./src
    - vault read sonarqube/kv/login >> sonar_url.txt
    - export SONAR_URL=$(cat sonar_url.txt | jq -r '.data.SONAR_URL')
    - vault read sonarqube/kv/secret >> sonar_login.txt
    - export SONAR_LOGIN=$(cat sonar_login.txt | jq -r '.data.SONAR_LOGIN')
    - export NAMESPACE=$(echo "$CI_PROJECT_NAMESPACE" | jq -Rr 'split("/") | .[1]')
    - /opt/sonar-scanner/sonar-scanner-6.0.0.4432-linux/bin/sonar-scanner begin -Dsonar.projectKey="com.ste.sa.$NAMESPACE.$CI_PROJECT_NAME" -Dsonar.sources=. -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dbitegarden.project.tag=South_America
    - dotnet-coverage collect "dotnet test ./src" -f xml -o "coverage.xml"
    - /opt/sonar-scanner/sonar-scanner-6.0.0.4432-linux/bin/sonar-scanner end -Dsonar.login=$SONAR_LOGIN