<<<<<<< Updated upstream
=======
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
>>>>>>> Stashed changes
using System.Reflection;
using System.Resources;

<<<<<<< Updated upstream
[assembly: AssemblyCompany("Stellantis")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCopyright("© Stellantis. All rights reserved.")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0.0")]
[assembly: AssemblyProduct("ProjectName")]
[assembly: AssemblyTitle("Stellantis.ProjectName.Infrastructure.Tests")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://gitlab.fcalatam.com/fca/ams/portal/api.git")]
=======
[assembly: System.Reflection.AssemblyCompanyAttribute("Stellantis")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© Stellantis. All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+bb828ae2bbc97d18d9a75ba6b8b3cd935f6d8962")]
[assembly: System.Reflection.AssemblyProductAttribute("Infrastructure.Tests")]
[assembly: System.Reflection.AssemblyTitleAttribute("Infrastructure.Tests")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://gitlab.fcalatam.com/fca/architecture/application/dotnetcore/base-project." +
    "git")]

// Gerado pela classe WriteCodeFragment do MSBuild.
>>>>>>> Stashed changes

[assembly: NeutralResourcesLanguage("en")]
