//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellantis.ProjectName.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KnowledgeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KnowledgeResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellantis.ProjectName.Application.Resources.KnowledgeResource", typeof(KnowledgeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Application is required.
        /// </summary>
        public static string ApplicationIsRequired {
            get {
                return ResourceManager.GetString("ApplicationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Association already exists..
        /// </summary>
        public static string AssociationAlreadyExists {
            get {
                return ResourceManager.GetString("AssociationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Association found.
        /// </summary>
        public static string AssociationFound {
            get {
                return ResourceManager.GetString("AssociationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Association not found..
        /// </summary>
        public static string AssociationNotFound {
            get {
                return ResourceManager.GetString("AssociationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It&apos;s not allowed to remove past associations..
        /// </summary>
        public static string CannotEditOrRemovePastAssociation {
            get {
                return ResourceManager.GetString("CannotEditOrRemovePastAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Member and application must belong to the same squad..
        /// </summary>
        public static string MemberApplicationMustBelongToTheSameSquad {
            get {
                return ResourceManager.GetString("MemberApplicationMustBelongToTheSameSquad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Member or application not found..
        /// </summary>
        public static string MemberApplicationNotFound {
            get {
                return ResourceManager.GetString("MemberApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Member is required..
        /// </summary>
        public static string MemberIsRequired {
            get {
                return ResourceManager.GetString("MemberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a It is only possible to remove if both belong to the leader&apos;s squad..
        /// </summary>
        public static string OnlyPossibleRemoveIfBelongToTheLeadersSquad {
            get {
                return ResourceManager.GetString("OnlyPossibleRemoveIfBelongToTheLeadersSquad", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only squad leader can remove..
        /// </summary>
        public static string SquadIsRequired
        {
            get
            {
                return ResourceManager.GetString("SquadIsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unsupported membership update..
        /// </summary>
        public static string UnsupportedMembershipUpdate {
            get {
                return ResourceManager.GetString("UnsupportedMembershipUpdate", resourceCulture);
            }
        }
    }
}
