//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellantis.ProjectName.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MemberResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemberResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellantis.ProjectName.Application.Resources.MemberResource", typeof(MemberResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member added successfully..
        /// </summary>
        public static string MemberAddedSuccessfully {
            get {
                return ResourceManager.GetString("MemberAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member cost must be greater than zero..
        /// </summary>
        public static string MemberCostMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MemberCostMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member deleted successfully..
        /// </summary>
        public static string MemberDeletedSuccessfully {
            get {
                return ResourceManager.GetString("MemberDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail already exists..
        /// </summary>
        public static string MemberEmailAlreadyExists {
            get {
                return ResourceManager.GetString("MemberEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member email invalid..
        /// </summary>
        public static string MemberEmailInvalid {
            get {
                return ResourceManager.GetString("MemberEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member email is required..
        /// </summary>
        public static string MemberEmailIsRequired {
            get {
                return ResourceManager.GetString("MemberEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member email validate length..
        /// </summary>
        public static string MemberEmailValidateLength {
            get {
                return ResourceManager.GetString("MemberEmailValidateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID not foound..
        /// </summary>
        public static string MemberIdNotFound {
            get {
                return ResourceManager.GetString("MemberIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name is required..
        /// </summary>
        public static string MemberNameIsRequired {
            get {
                return ResourceManager.GetString("MemberNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member name validate length..
        /// </summary>
        public static string MemberNameValidateLength {
            get {
                return ResourceManager.GetString("MemberNameValidateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All required fields must be completed..
        /// </summary>
        public static string MemberRequiredFieldsMissing {
            get {
                return ResourceManager.GetString("MemberRequiredFieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member role is required..
        /// </summary>
        public static string MemberRoleIsRequired {
            get {
                return ResourceManager.GetString("MemberRoleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member role validate length..
        /// </summary>
        public static string MemberRoleValidateLength {
            get {
                return ResourceManager.GetString("MemberRoleValidateLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member updated successfully..
        /// </summary>
        public static string MemberUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("MemberUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
