//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellantis.ProjectName.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellantis.ProjectName.Application.Resources.NotificationResources", typeof(NotificationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, you have been associated with an already created feedback: {1}..
        /// </summary>
        public static string FeedbackAddMember {
            get {
                return ResourceManager.GetString("FeedbackAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, a new feedback associated with you has been created: {1}..
        /// </summary>
        public static string FeedbackCreatedMessage {
            get {
                return ResourceManager.GetString("FeedbackCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, you are no longer associated with the feedback: {1}..
        /// </summary>
        public static string FeedbackRemoveMember {
            get {
                return ResourceManager.GetString("FeedbackRemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, the status of the feedback &apos;{1}&apos;, associated with you, has been changed to: {2}..
        /// </summary>
        public static string FeedbackStatusChangedMessage {
            get {
                return ResourceManager.GetString("FeedbackStatusChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, you have been associated with an already created incident: {1}..
        /// </summary>
        public static string IncidentAddMember {
            get {
                return ResourceManager.GetString("IncidentAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, a new incident associated with you has been created: {1}..
        /// </summary>
        public static string IncidentCreatedMessage {
            get {
                return ResourceManager.GetString("IncidentCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, you are no longer associated with the incident: {1}..
        /// </summary>
        public static string IncidentRemoveMember {
            get {
                return ResourceManager.GetString("IncidentRemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hello {0}, the status of the incident &apos;{1}&apos;, associated with you, has been changed to: {2}..
        /// </summary>
        public static string IncidentStatusChangedMessage {
            get {
                return ResourceManager.GetString("IncidentStatusChangedMessage", resourceCulture);
            }
        }
    }
}
