//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellantis.ProjectName.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PartNumberResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartNumberResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellantis.ProjectName.Application.Resources.PartNumberResources", typeof(PartNumberResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already with this code...
        /// </summary>
        public static string AlreadyExistCode {
            get {
                return ResourceManager.GetString("AlreadyExistCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exist for this supplier..
        /// </summary>
        public static string AlreadyExistForThisSupplier {
            get {
                return ResourceManager.GetString("AlreadyExistForThisSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists for this vehicle..
        /// </summary>
        public static string AlreadyExistForThisVehicle {
            get {
                return ResourceManager.GetString("AlreadyExistForThisVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required..
        /// </summary>
        public static string CodeIsRequired {
            get {
                return ResourceManager.GetString("CodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code maxi length 11..
        /// </summary>
        public static string CodeMaxLength {
            get {
                return ResourceManager.GetString("CodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required..
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate partnumbers..
        /// </summary>
        public static string Duplicated {
            get {
                return ResourceManager.GetString("Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis is required..
        /// </summary>
        public static string TypeIsRequired {
            get {
                return ResourceManager.GetString("TypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted as it is linked to a supplier or vehicle..
        /// </summary>
        public static string Undeleted {
            get {
                return ResourceManager.GetString("Undeleted", resourceCulture);
            }
        }
    }
}
