//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stellantis.ProjectName.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stellantis.ProjectName.Infrastructure.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassi already exists.
        /// </summary>
        public static string AlreadyExistChassi {
            get {
                return ResourceManager.GetString("AlreadyExistChassi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code already exists.
        /// </summary>
        public static string AlreadyExistCode {
            get {
                return ResourceManager.GetString("AlreadyExistCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist for this supplier(s).
        /// </summary>
        public static string AlreadyExistPartNumberSupplier {
            get {
                return ResourceManager.GetString("AlreadyExistPartNumberSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exist for this vehicle(s).
        /// </summary>
        public static string AlreadyExistPartNumberVehicle {
            get {
                return ResourceManager.GetString("AlreadyExistPartNumberVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate drawings.
        /// </summary>
        public static string DuplicatedDrawings {
            get {
                return ResourceManager.GetString("DuplicatedDrawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered.
        /// </summary>
        public static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The drawing.
        /// </summary>
        public static string TheDrawing {
            get {
                return ResourceManager.GetString("TheDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing cannot be deleted as it is linked to a supplier or vehicle.
        /// </summary>
        public static string UndeletedDrawing {
            get {
                return ResourceManager.GetString("UndeletedDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
