//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Stellantis")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© Stellantis. All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+d26161775e8aae090c3b242086dad95503c9382c")]
[assembly: System.Reflection.AssemblyProductAttribute("ProjectName")]
[assembly: System.Reflection.AssemblyTitleAttribute("Stellantis.ProjectName.Domain")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", ("https://gitlab.fcalatam.com/fca/architecture/application/dotnetcore/base-project." +
    "git"))]

// Generated by the MSBuild WriteCodeFragment class.

