// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;
[assembly: SuppressMessage("Reliability", "CA2000:Descartar objetos antes de perder o escopo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.CloseIssueAsync(System.Int32)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Design", "CA1062:Validar argumentos de métodos públicos", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.UpdateIssueAsync(System.Int32,Stellantis.ProjectName.Application.DtoService.GitLabIssueDto)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "CA2234:Passar objetos do URI do sistema em vez de cadeias de caracteres", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.CreateIssueAsync(Stellantis.ProjectName.Application.DtoService.GitLabIssueDto)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2000:Descartar objetos antes de perder o escopo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.UpdateIssueAsync(System.Int32,Stellantis.ProjectName.Application.DtoService.GitLabIssueDto)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "CA2234:Passar objetos do URI do sistema em vez de cadeias de caracteres", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.GetIssueAsync(System.Int32)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Design", "CA1062:Validar argumentos de métodos públicos", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.CreateIssueAsync(Stellantis.ProjectName.Application.DtoService.GitLabIssueDto)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "CA2234:Passar objetos do URI do sistema em vez de cadeias de caracteres", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.CloseIssueAsync(System.Int32)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Usage", "CA2234:Passar objetos do URI do sistema em vez de cadeias de caracteres", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.UpdateIssueAsync(System.Int32,Stellantis.ProjectName.Application.DtoService.GitLabIssueDto)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2000:Descartar objetos antes de perder o escopo", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.GitLabIssueService.CreateIssueAsync(Stellantis.ProjectName.Application.DtoService.GitLabIssueDto)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Globalization", "CA1307:Especificar StringComparison para garantir o esclarecimento", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.ApplicationExportService.CsvSafe(System.String)~System.String")]
[assembly: SuppressMessage("Performance", "CA1847:Usar o literal char para uma pesquisa de caractere único", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.ApplicationExportService.CsvSafe(System.String)~System.String")]
[assembly: SuppressMessage("Performance", "CA1860:Evite usar o método de extensão 'Enumerable.Any()'", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.ApplicationExportService.ExportApplicationAsync(System.Int32)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: SuppressMessage("Globalization", "CA1305:Especificar IFormatProvider", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.ApplicationExportService.ExportToPdfAsync(Stellantis.ProjectName.Application.Models.Filters.ApplicationFilter)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: SuppressMessage("Design", "CA1062:Validar argumentos de métodos públicos", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.ApplicationExportService.ExportToPdfAsync(Stellantis.ProjectName.Application.Models.Filters.ApplicationFilter)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: SuppressMessage("Design", "CA1062:Validar argumentos de métodos públicos", Justification = "<Pendente>", Scope = "member", Target = "~M:Stellantis.ProjectName.Application.Services.ApplicationExportService.ExportToCsvAsync(Stellantis.ProjectName.Application.Models.Filters.ApplicationFilter)~System.Threading.Tasks.Task{System.Byte[]}")]
[assembly: SuppressMessage("Performance", "CA1819:As propriedades não devem retornar matrizes", Justification = "<Pendente>", Scope = "member", Target = "~P:Stellantis.ProjectName.Application.DtoService.GitLabIssueDto.Labels")]
[assembly: SuppressMessage("Performance", "CA1819:As propriedades não devem retornar matrizes", Justification = "<Pendente>", Scope = "member", Target = "~P:Stellantis.ProjectName.Application.DtoService.GitLabIssueDto.RemoveLabels")]
[assembly: SuppressMessage("Design", "CA1002:Não expor listas genéricas", Justification = "<Pendente>", Scope = "member", Target = "~P:Stellantis.ProjectName.Application.Models.Filters.IncidentFilter.MemberIds")]
[assembly: SuppressMessage("Usage", "CA2227:As propriedades de coleção devem ser somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~P:Stellantis.ProjectName.Application.Models.Filters.IncidentFilter.MemberIds")]
[assembly: SuppressMessage("Design", "CA1002:Não expor listas genéricas", Justification = "<Pendente>", Scope = "member", Target = "~P:Stellantis.ProjectName.Application.Models.Filters.FeedbackFilter.MemberId")]
[assembly: SuppressMessage("Usage", "CA2227:As propriedades de coleção devem ser somente leitura", Justification = "<Pendente>", Scope = "member", Target = "~P:Stellantis.ProjectName.Application.Models.Filters.FeedbackFilter.MemberId")]

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
// FAZZZ O Lint
