//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("74668664-49c0-4c0b-a519-a16c41b7e881")]
[assembly: System.Reflection.AssemblyCompanyAttribute("Stellantis")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© Stellantis. All rights reserved.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+b5b78ceba10571d8aa97213b7105d61bd7e52270")]
[assembly: System.Reflection.AssemblyProductAttribute("ProjectName")]
[assembly: System.Reflection.AssemblyTitleAttribute("Stellantis.ProjectName.WebApi")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://gitlab.fcalatam.com/fca/architecture/application/dotnetcore/base-project." +
    "git")]

// Gerado pela classe WriteCodeFragment do MSBuild.

